#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EmmaAndroid.Resource", IsApplication=true)]

namespace EmmaAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Tesseract.Droid.Resource.String.ApplicationName = global::EmmaAndroid.Resource.String.ApplicationName;
			global::Tesseract.Droid.Resource.String.Hello = global::EmmaAndroid.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::EmmaAndroid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::EmmaAndroid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::EmmaAndroid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int algorithm = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int audio_in = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int audio_out = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int audio_out_deactivated = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int camera = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int camera_barcodesearch = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int camera_search = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int camera_textsearch = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int emergency = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int flashlight = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int home = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int hospital = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int latest_targets = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int list = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int map = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int medicine = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int medicine2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int newNote = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int note = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int plus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int search = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int settings = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05002a
			public const int buttonAudioOut = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int buttonImageSearch = 2131034153;
			
			// aapt resource value: 0x7f050030
			public const int buttonSave = 2131034160;
			
			// aapt resource value: 0x7f050028
			public const int buttonSettings = 2131034152;
			
			// aapt resource value: 0x7f050039
			public const int contentFrame = 2131034169;
			
			// aapt resource value: 0x7f05002f
			public const int editAddress = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int editText = 2131034161;
			
			// aapt resource value: 0x7f05002e
			public const int editTitle = 2131034158;
			
			// aapt resource value: 0x7f050001
			public const int frameLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int imageButton10 = 2131034125;
			
			// aapt resource value: 0x7f050035
			public const int imageButton11 = 2131034165;
			
			// aapt resource value: 0x7f05000b
			public const int imageButton12 = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int imageButton7 = 2131034119;
			
			// aapt resource value: 0x7f050033
			public const int imageButton8 = 2131034163;
			
			// aapt resource value: 0x7f050004
			public const int imageButtonAdd = 2131034116;
			
			// aapt resource value: 0x7f05001e
			public const int imageButtonAlgorithm = 2131034142;
			
			// aapt resource value: 0x7f050036
			public const int imageButtonCamera = 2131034166;
			
			// aapt resource value: 0x7f050024
			public const int imageButtonEmergencyMedic = 2131034148;
			
			// aapt resource value: 0x7f050009
			public const int imageButtonFlashlight = 2131034121;
			
			// aapt resource value: 0x7f05002b
			public const int imageButtonLatest = 2131034155;
			
			// aapt resource value: 0x7f050021
			public const int imageButtonList = 2131034145;
			
			// aapt resource value: 0x7f050014
			public const int imageButtonMedic = 2131034132;
			
			// aapt resource value: 0x7f05002c
			public const int imageButtonNavigateHome = 2131034156;
			
			// aapt resource value: 0x7f05001c
			public const int imageButtonNavigation = 2131034140;
			
			// aapt resource value: 0x7f050037
			public const int imageButtonNew = 2131034167;
			
			// aapt resource value: 0x7f050018
			public const int imageButtonNote = 2131034136;
			
			// aapt resource value: 0x7f050022
			public const int imageButtonPhotoSearchMedic = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int imageButtonPhotoTextSearchMedic = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int imageButtonSeachMedic = 2131034149;
			
			// aapt resource value: 0x7f05002d
			public const int imageButtonSearch = 2131034157;
			
			// aapt resource value: 0x7f050016
			public const int imageButtonVoice = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout1 = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout10 = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout2 = 2131034130;
			
			// aapt resource value: 0x7f050023
			public const int linearLayout3 = 2131034147;
			
			// aapt resource value: 0x7f050027
			public const int linearLayout5 = 2131034151;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout6 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout7 = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout8 = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int linearLayout9 = 2131034138;
			
			// aapt resource value: 0x7f050011
			public const int relativeLayout1 = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int relativeLayout2 = 2131034137;
			
			// aapt resource value: 0x7f05000f
			public const int relativeLayout20 = 2131034127;
			
			// aapt resource value: 0x7f050020
			public const int relativeLayout21 = 2131034144;
			
			// aapt resource value: 0x7f05001b
			public const int relativeLayout22 = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int relativeLayout23 = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int relativeLayout24 = 2131034143;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout25 = 2131034112;
			
			// aapt resource value: 0x7f050015
			public const int relativeLayout26 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int relativeLayout27 = 2131034135;
			
			// aapt resource value: 0x7f050038
			public const int relativeLayout28 = 2131034168;
			
			// aapt resource value: 0x7f050006
			public const int relativeLayout4 = 2131034118;
			
			// aapt resource value: 0x7f050032
			public const int relativeLayout5 = 2131034162;
			
			// aapt resource value: 0x7f050008
			public const int relativeLayout6 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int relativeLayout7 = 2131034122;
			
			// aapt resource value: 0x7f050034
			public const int relativeLayout8 = 2131034164;
			
			// aapt resource value: 0x7f05000c
			public const int relativeLayout9 = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int scrollView1 = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Medic = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Navigation = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NavigationAdd = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Note = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NoteDetail = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscanneractivitylayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscannerfragmentlayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
